-- AlterTable
ALTER TABLE `Widget` ADD COLUMN `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `source` ENUM('EVENTS', 'WEBHOOK') NOT NULL DEFAULT 'EVENTS';

-- CreateTable
CREATE TABLE `WidgetPoint` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `widgetId` INTEGER NOT NULL,
    `data` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `WidgetPoint` ADD CONSTRAINT `WidgetPoint_widgetId_fkey` FOREIGN KEY (`widgetId`) REFERENCES `Widget`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
